services:
  django-api:
    container_name: django_api_c
    build: .
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - taskflow-pg
      - redis
    volumes:
      - ./:/app
    command: >
      sh -c "
        python manage.py collectstatic --no-input &&
        python manage.py makemigrations &&
        python manage.py migrate --no-input && 
        python manage.py createsuperuser --no-input || true &&
        daphne -b 0.0.0.0 -p 8001 core.project.asgi:application
      "

  taskflow-pg:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis_broker
    ports:
      - "6379:6379"
    restart: unless-stopped

  celery_worker:
    build: .
    container_name: celery_worker
    env_file:
      - ./.env
    command: celery -A core.project:celery_app worker --loglevel=info
    volumes:
      - ./:/app
    depends_on:
      - redis
      - django-api
    restart: unless-stopped

volumes:
  db_data:
