# Generated by Django 6.0.4 on 2026-06-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='spent_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Spent hours'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Todo'), ('in_progress', 'In Progress'), ('review', 'Review'), ('done', 'Done')], default='todo', verbose_name='Status'),
        ),
    ]
