# Generated by Django 6.0.4 on 2026-06-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_priority_alter_task_spent_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Estimated hours'),
        ),
        migrations.AlterField(
            model_name='task',
            name='spent_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Spent hours'),
        ),
    ]
